# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# addingFields.py
# Created on: 2017-05-25 09:28:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: addingFields <WT_Pipe_main_surf> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
WT_Pipe_main_surf = arcpy.GetParameterAsText(0)
if WT_Pipe_main_surf == '#' or not WT_Pipe_main_surf:
    WT_Pipe_main_surf = "\\\\watis\\public\\InternsSpring2017\\Spring2017_WT_GeoDb.mdb\\Spring2017_WT\\WT_Pipe_main_surf" # provide a default value if unspecified

# Local variables:
WT_Pipe_main_surf__2_ = WT_Pipe_main_surf
WT_Pipe_main_surf__3_ = WT_Pipe_main_surf__2_
WT_Pipe_main_surf__6_ = WT_Pipe_main_surf__3_
WT_Pipe_main_surf__5_ = WT_Pipe_main_surf__6_
WT_Pipe_main_surf__4_ = WT_Pipe_main_surf__5_
WT_Pipe_main_surf__8_ = WT_Pipe_main_surf__4_
WT_Pipe_main_surf__7_ = WT_Pipe_main_surf__8_
WT_Pipe_main_surf__12_ = WT_Pipe_main_surf__7_
WT_Pipe_main_surf__10_ = WT_Pipe_main_surf__12_
WT_Pipe_main_surf__11_ = WT_Pipe_main_surf__10_
WT_Pipe_main_surf__9_ = WT_Pipe_main_surf__11_
WT_Pipe_main_surf__13_ = WT_Pipe_main_surf__9_

# Process: Add Field
arcpy.AddField_management(WT_Pipe_main_surf, "Risk_Pipe", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(WT_Pipe_main_surf__2_, "Risk_TruckRoute", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(WT_Pipe_main_surf__3_, "Risk_School", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(WT_Pipe_main_surf__6_, "Risk_Business", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (5)
arcpy.AddField_management(WT_Pipe_main_surf__5_, "Risk_Facility", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (6)
arcpy.AddField_management(WT_Pipe_main_surf__4_, "Risk_Park", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (7)
arcpy.AddField_management(WT_Pipe_main_surf__8_, "Risk_PumpStation", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (8)
arcpy.AddField_management(WT_Pipe_main_surf__7_, "Risk_Creek", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (9)
arcpy.AddField_management(WT_Pipe_main_surf__12_, "Risk_Diameter", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (10)
arcpy.AddField_management(WT_Pipe_main_surf__10_, "Likelihood", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (11)
arcpy.AddField_management(WT_Pipe_main_surf__11_, "Consequence", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (12)
arcpy.AddField_management(WT_Pipe_main_surf__9_, "Risk_Index", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

