# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# addingNewItem.py
# Created on: 2017-05-25 09:28:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: addingNewItem <WT_Pipe_main_surf> <Source_Layer> <Field_Name> <Field_Name__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
WT_Pipe_main_surf = arcpy.GetParameterAsText(0)
if WT_Pipe_main_surf == '#' or not WT_Pipe_main_surf:
    WT_Pipe_main_surf = "\\\\watis\\public\\InternsSpring2017\\Spring2017_WT_GeoDb.mdb\\Spring2017_WT\\WT_Pipe_main_surf" # provide a default value if unspecified

Source_Layer = arcpy.GetParameterAsText(1)
if Source_Layer == '#' or not Source_Layer:
    Source_Layer = "\\\\watis\\public\\InternsSpring2017\\Spring2017_WT_GeoDb.mdb\\Public Works\\FC_FacAllSite_V" # provide a default value if unspecified

Field_Name = arcpy.GetParameterAsText(2)
if Field_Name == '#' or not Field_Name:
    Field_Name = "Risk_something" # provide a default value if unspecified

Field_Name__2_ = arcpy.GetParameterAsText(3)
if Field_Name__2_ == '#' or not Field_Name__2_:
    Field_Name__2_ = "Risk_something" # provide a default value if unspecified

# Local variables:
Output_Feature_Class = WT_Pipe_main_surf
WT_Pipe_main_surf__2_ = Output_Feature_Class
WT_Pipe_main_surf_test_Layer = "WT_Pipe_main_surf_Layer2"
WT_Pipe_main_surf_test_Layer__2_ = WT_Pipe_main_surf_test_Layer
WT_Pipe_main_surf_test = Source_Layer
WT_Pipe_main_surf_test__2_ = Source_Layer
WT_Pipe_main_surf_test__7_ = Source_Layer
WT_Pipe_main_surf_Layer2 = WT_Pipe_main_surf_test_Layer__2_
WT_Pipe_main_surf_Layer2__2_ = WT_Pipe_main_surf_test
WT_Pipe_main_surf_Layer2__3_ = WT_Pipe_main_surf_test__2_
WT_Pipe_main_surf_Layer2__4_ = WT_Pipe_main_surf_test__7_

# Process: Add Field
arcpy.AddField_management(WT_Pipe_main_surf, Field_Name, "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Output_Feature_Class, Field_Name__2_, "1", "PYTHON", "")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(WT_Pipe_main_surf__2_, WT_Pipe_main_surf_test_Layer, "", "", "OBJECTID OBJECTID VISIBLE NONE;GID GID VISIBLE NONE;LAYER LAYER VISIBLE NONE;PIPEID PIPEID VISIBLE NONE;MATERIAL MATERIAL VISIBLE NONE;MaterialDesc MaterialDesc VISIBLE NONE;DIAMETER DIAMETER VISIBLE NONE;MEASUREDLE MEASUREDLE VISIBLE NONE;ACTUALLENG ACTUALLENG VISIBLE NONE;INSTALLATI INSTALLATI VISIBLE NONE;DRAWINGNO DRAWINGNO VISIBLE NONE;SOURCE SOURCE VISIBLE NONE;PressureZo PressureZo VISIBLE NONE;RiskCondition RiskCondition VISIBLE NONE;RiskFactor RiskFactor VISIBLE NONE;RiskIndex RiskIndex VISIBLE NONE;Shape Shape VISIBLE NONE;Z_Min Z_Min VISIBLE NONE;Z_Max Z_Max VISIBLE NONE;Z_Mean Z_Mean VISIBLE NONE;SLength SLength VISIBLE NONE;Min_Slope Min_Slope VISIBLE NONE;Max_Slope Max_Slope VISIBLE NONE;Avg_Slope Avg_Slope VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Risk_something Risk_something VISIBLE NONE")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(WT_Pipe_main_surf_test_Layer, "WITHIN_A_DISTANCE", Source_Layer, "1000 Feet", "NEW_SELECTION", "NOT_INVERT")

# Process: Calculate Field (2)
arcpy.CalculateField_management(WT_Pipe_main_surf_test_Layer__2_, Field_Name__2_, "2", "PYTHON", "")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(WT_Pipe_main_surf_Layer2, "WITHIN_A_DISTANCE", Source_Layer, "500 Feet", "NEW_SELECTION", "NOT_INVERT")

# Process: Calculate Field (3)
arcpy.CalculateField_management(WT_Pipe_main_surf_test, Field_Name__2_, "3", "PYTHON", "")

# Process: Select Layer By Location (3)
arcpy.SelectLayerByLocation_management(WT_Pipe_main_surf_Layer2__2_, "WITHIN_A_DISTANCE", Source_Layer, "100 Feet", "NEW_SELECTION", "NOT_INVERT")

# Process: Calculate Field (4)
arcpy.CalculateField_management(WT_Pipe_main_surf_test__2_, Field_Name__2_, "4", "PYTHON", "")

# Process: Select Layer By Location (4)
arcpy.SelectLayerByLocation_management(WT_Pipe_main_surf_Layer2__3_, "INTERSECT", Source_Layer, "0 Feet", "NEW_SELECTION", "NOT_INVERT")

# Process: Calculate Field (5)
arcpy.CalculateField_management(WT_Pipe_main_surf_test__7_, Field_Name__2_, "5", "PYTHON", "")

