# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Daimeter.py
# Created on: 2017-05-25 09:29:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Daimeter <WT_Pipe_main_surf> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
WT_Pipe_main_surf = arcpy.GetParameterAsText(0)
if WT_Pipe_main_surf == '#' or not WT_Pipe_main_surf:
    WT_Pipe_main_surf = "\\\\watis\\public\\InternsSpring2017\\Spring2017_WT_GeoDb.mdb\\Spring2017_WT\\WT_Pipe_main_surf" # provide a default value if unspecified

# Local variables:
WT_Pipe_main_surf_test = WT_Pipe_main_surf

# Process: Calculate Field
arcpy.CalculateField_management(WT_Pipe_main_surf, "Risk_Diameter", "diameter( !DIAMETER!)", "PYTHON", "def diameter(a):\\n# a = diamter\\n\\n    if a == None:\\n       return None\\n\\n# diamter\\n    if a <= 10:\\n        return 1\\n    elif a > 10 and a <=16:\\n        return 2\\n    elif a > 16 and a <=36:\\n        return 3\\n    else:\\n        return 5")

