# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Truck_Route.py
# Created on: 2017-05-25 09:30:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Truck_Route <WT_Pipe_main_surf> <TR_TrkRte> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
WT_Pipe_main_surf = arcpy.GetParameterAsText(0)
if WT_Pipe_main_surf == '#' or not WT_Pipe_main_surf:
    WT_Pipe_main_surf = "\\\\watis\\public\\InternsSpring2017\\Spring2017_WT_GeoDb.mdb\\Spring2017_WT\\WT_Pipe_main_surf" # provide a default value if unspecified

TR_TrkRte = arcpy.GetParameterAsText(1)
if TR_TrkRte == '#' or not TR_TrkRte:
    TR_TrkRte = "\\\\watis\\public\\InternsSpring2017\\Spring2017_WT_GeoDb.mdb\\Transportation\\TR_TrkRte" # provide a default value if unspecified

# Local variables:
WT_Pipe_main_surf_test__12_ = WT_Pipe_main_surf
WT_Pipe_main_surf_Layer2 = "WT_Pipe_main_surf_Layer2"
WT_Pipe_main_surf_Layer2__2_ = WT_Pipe_main_surf_Layer2
WT_Pipe_main_surf_test__5_ = WT_Pipe_main_surf_Layer2__2_

# Process: Calculate Field
arcpy.CalculateField_management(WT_Pipe_main_surf, "Risk_TruckRoute", "1", "PYTHON", "")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(WT_Pipe_main_surf_test__12_, WT_Pipe_main_surf_Layer2, "", "", "OBJECTID OBJECTID VISIBLE NONE;GID GID VISIBLE NONE;LAYER LAYER VISIBLE NONE;PIPEID PIPEID VISIBLE NONE;MATERIAL MATERIAL VISIBLE NONE;MaterialDesc MaterialDesc VISIBLE NONE;DIAMETER DIAMETER VISIBLE NONE;MEASUREDLE MEASUREDLE VISIBLE NONE;ACTUALLENG ACTUALLENG VISIBLE NONE;INSTALLATI INSTALLATI VISIBLE NONE;DRAWINGNO DRAWINGNO VISIBLE NONE;SOURCE SOURCE VISIBLE NONE;PressureZo PressureZo VISIBLE NONE;RiskCondition RiskCondition VISIBLE NONE;RiskFactor RiskFactor VISIBLE NONE;RiskIndex RiskIndex VISIBLE NONE;Shape Shape VISIBLE NONE;Z_Min Z_Min VISIBLE NONE;Z_Max Z_Max VISIBLE NONE;Z_Mean Z_Mean VISIBLE NONE;SLength SLength VISIBLE NONE;Min_Slope Min_Slope VISIBLE NONE;Max_Slope Max_Slope VISIBLE NONE;Avg_Slope Avg_Slope VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Risk_Pipe Risk_Pipe VISIBLE NONE;Risk_TruckRoute Risk_TruckRoute VISIBLE NONE;Risk_School Risk_School VISIBLE NONE;Risk_Business Risk_Business VISIBLE NONE;Risk_Facility Risk_Facility VISIBLE NONE;Risk_Park Risk_Park VISIBLE NONE;Risk_PumpStation Risk_PumpStation VISIBLE NONE;Risk_Creek Risk_Creek VISIBLE NONE;Risk_Diameter Risk_Diameter VISIBLE NONE;Likelihood Likelihood VISIBLE NONE;Consequence Consequence VISIBLE NONE;Risk_Index Risk_Index VISIBLE NONE")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(WT_Pipe_main_surf_Layer2, "WITHIN_A_DISTANCE", TR_TrkRte, "75 Feet", "NEW_SELECTION", "NOT_INVERT")

# Process: Calculate Field (2)
arcpy.CalculateField_management(WT_Pipe_main_surf_Layer2__2_, "Risk_TruckRoute", "5", "PYTHON", "")

